[build-system]
requires = ["maturin>=1.13,<2.0"]  # requires generate-stubs which is maturin 1.13+
build-backend = "maturin"

[project]
name = "dependency_cache"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
keywords = ["caching", "dependency-graph", "invalidation"]
version = "0.1.1"
description = "A caching system for object methods that utilises a dependency graph to track relationships and trigger invalidation"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "matplotlib>=3.7.5",
    "networkx>=3.1",
]

[project.urls]
Homepage = "https://github.com/XtdWt/dependency_cache"
Repository = "https://github.com/XtdWt/dependency_cache"
Issues = "https://github.com/XtdWt/dependency_cache/issues"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
