from typing import Any, final

class DependencyCacheBase:
    def __new__(cls, /, *_args, **_kwargs) -> DependencyCacheBase: ...
    def clear_cache(self, /) -> None: ...
    def get_cached_value(self, /, method_name: str, **kwargs) -> Any | None: ...
    def get_cached_value_by_hash(self, /, hash: int) -> Any | None: ...
    def get_cached_values(self, /) -> dict: ...
    def get_dependency_graph(self, /) -> dict: ...
    def get_validation_state(self, /) -> dict: ...
    def update_cached_value(
        self, /, method_name: str, value: Any, **kwargs
    ) -> None: ...

@final
class automagically_dependency_cached:
    def __call__(self, /, func: Any) -> Any: ...
    def __new__(
        cls,
        /,
        use_cache: bool = True,
        dependencies: Any | None = None,
        track_runtime_dependencies: bool = True,
    ) -> automagically_dependency_cached: ...

@final
class dependency_cached:
    def __call__(self, /, func: Any) -> Any: ...
    def __new__(
        cls,
        /,
        use_cache: bool = True,
        dependencies: Any | None = None,
        track_runtime_dependencies: bool = False,
    ) -> dependency_cached: ...
