from collections.abc import Sequence
from typing import Any, final

class DependencyCacheBase:
    def __new__(cls, /, *_args, **_kwargs) -> DependencyCacheBase: ...
    def clear_cache(self, /) -> None: ...
    def current_cache(self, /) -> dict: ...
    def current_cache_validation(self, /) -> dict: ...
    def current_graph(self, /) -> dict: ...
    def get_cached_value(self, /, name: str) -> Any |None: ...
    def update_cached_value(self, /, name: str, value: Any) -> None: ...

@final
class dependency_cached:
    def __call__(self, /, func: Any) -> Any: ...
    def __new__(cls, /, use_cache: bool = True, dependencies: Sequence[str] = ...) -> dependency_cached: ...
